export type ExperimentCommand = {
  id: number;
  lab: 'well' | 'oscillator' | 'scattering' | 'double-well' | 'rotor' | 'hydrogen' | 'spin';
  mode?: 'stationary' | 'evolution';
  quantumNumber?: number;
  preset?: string;
  time?: number;
  scale?: number;
  potential?: 'barrier' | 'gaussian' | 'well';
  height?: number;
  width?: number;
  momentum?: number;
  sigma?: number;
  progress?: number;
  barrier?: number;
  separation?: number;
  principal?: number;
  angular?: number;
  magnetic?: number;
  inertia?: number;
  basis?: 'complex' | 'real';
  atomicView?: 'slice' | 'radial';
  plane?: 'xz' | 'xy' | 'yz' | 'oblique';
  spinTheta?: number;
  spinPhi?: number;
  spinOmega?: number;
  spinField?: 'x' | 'y' | 'z' | 'tilted';
  spinMeasure?: 'x' | 'y' | 'z';
};
